"""
扩展技能树系统 - 为每个职业创建完整的技能树
"""
from typing import Dict, List, Tuple
from systems.skills.skill_tree import SkillTree, SkillNode, NodeType


def create_barbarian_tree() -> List[SkillNode]:
    return [
        SkillNode(id="barb_strength_1", name="力量训练 I", description="增加力量",
                 node_type=NodeType.ATTRIBUTE, position=(0, 1), max_points=5,
                 effects={"strength": 3}, required_level=1),
        SkillNode(id="barb_strength_2", name="力量训练 II", description="大幅增加力量",
                 node_type=NodeType.ATTRIBUTE, position=(0, 2), max_points=5,
                 effects={"strength": 5}, prerequisites=["barb_strength_1"], required_level=10),
        SkillNode(id="barb_vitality_1", name="生命强化 I", description="增加生命值",
                 node_type=NodeType.ATTRIBUTE, position=(1, 1), max_points=5,
                 effects={"max_health": 20}, required_level=1),
        SkillNode(id="barb_vitality_2", name="生命强化 II", description="大幅增加生命值",
                 node_type=NodeType.ATTRIBUTE, position=(1, 2), max_points=5,
                 effects={"max_health": 40}, prerequisites=["barb_vitality_1"], required_level=15),
        SkillNode(id="barb_armor_1", name="钢铁之躯", description="增加护甲",
                 node_type=NodeType.PASSIVE, position=(2, 1), max_points=5,
                 effects={"armor": 10}, required_level=5),
        SkillNode(id="barb_crit_1", name="狂暴打击", description="增加暴击率",
                 node_type=NodeType.PASSIVE, position=(3, 1), max_points=5,
                 effects={"crit_chance": 2}, prerequisites=["barb_strength_1"], required_level=10),
        SkillNode(id="barb_crit_dmg_1", name="致命一击", description="增加暴击伤害",
                 node_type=NodeType.PASSIVE, position=(3, 2), max_points=5,
                 effects={"crit_damage": 10}, prerequisites=["barb_crit_1"], required_level=20),
        SkillNode(id="barb_fury_1", name="怒气掌控", description="增加怒气生成",
                 node_type=NodeType.PASSIVE, position=(4, 1), max_points=5,
                 effects={"fury_generation": 10}, required_level=5),
        SkillNode(id="barb_rend_1", name="撕裂伤口", description="攻击造成流血",
                 node_type=NodeType.PASSIVE, position=(5, 1), max_points=3,
                 effects={"bleed_chance": 5}, prerequisites=["barb_crit_1"], required_level=25),
        SkillNode(id="barb_resist_1", name="自然抗性", description="增加所有抗性",
                 node_type=NodeType.PASSIVE, position=(2, 2), max_points=5,
                 effects={"all_resist": 5}, prerequisites=["barb_armor_1"], required_level=15),
        SkillNode(id="barb_life_steal_1", name="嗜血", description="攻击回复生命",
                 node_type=NodeType.PASSIVE, position=(4, 2), max_points=3,
                 effects={"life_steal": 1}, prerequisites=["barb_fury_1"], required_level=30),
        SkillNode(id="barb_damage_1", name="狂战士", description="增加伤害",
                 node_type=NodeType.PASSIVE, position=(6, 1), max_points=5,
                 effects={"damage_percent": 3}, prerequisites=["barb_rend_1"], required_level=35),
    ]


def create_wizard_tree() -> List[SkillNode]:
    return [
        SkillNode(id="wiz_int_1", name="智力训练 I", description="增加智力",
                 node_type=NodeType.ATTRIBUTE, position=(0, 1), max_points=5,
                 effects={"intelligence": 3}, required_level=1),
        SkillNode(id="wiz_int_2", name="智力训练 II", description="大幅增加智力",
                 node_type=NodeType.ATTRIBUTE, position=(0, 2), max_points=5,
                 effects={"intelligence": 5}, prerequisites=["wiz_int_1"], required_level=10),
        SkillNode(id="wiz_mana_1", name="法力强化 I", description="增加法力值",
                 node_type=NodeType.ATTRIBUTE, position=(1, 1), max_points=5,
                 effects={"max_mana": 20}, required_level=1),
        SkillNode(id="wiz_mana_2", name="法力强化 II", description="大幅增加法力值",
                 node_type=NodeType.ATTRIBUTE, position=(1, 2), max_points=5,
                 effects={"max_mana": 40}, prerequisites=["wiz_mana_1"], required_level=15),
        SkillNode(id="wiz_mana_regen_1", name="法力回复", description="增加法力回复",
                 node_type=NodeType.PASSIVE, position=(2, 1), max_points=5,
                 effects={"mana_regen": 2}, required_level=5),
        SkillNode(id="wiz_spell_dmg_1", name="奥术精通", description="增加法术伤害",
                 node_type=NodeType.PASSIVE, position=(3, 1), max_points=5,
                 effects={"spell_damage_percent": 3}, prerequisites=["wiz_int_1"], required_level=10),
        SkillNode(id="wiz_cast_speed_1", name="快速施法", description="增加施法速度",
                 node_type=NodeType.PASSIVE, position=(3, 2), max_points=5,
                 effects={"cast_speed": 2}, prerequisites=["wiz_spell_dmg_1"], required_level=20),
        SkillNode(id="wiz_fire_dmg_1", name="火焰掌控", description="增加火焰伤害",
                 node_type=NodeType.PASSIVE, position=(4, 1), max_points=5,
                 effects={"fire_damage_percent": 5}, required_level=10),
        SkillNode(id="wiz_cold_dmg_1", name="冰冷掌控", description="增加冰冷伤害",
                 node_type=NodeType.PASSIVE, position=(4, 2), max_points=5,
                 effects={"cold_damage_percent": 5}, required_level=10),
        SkillNode(id="wiz_light_dmg_1", name="闪电掌控", description="增加闪电伤害",
                 node_type=NodeType.PASSIVE, position=(4, 3), max_points=5,
                 effects={"lightning_damage_percent": 5}, required_level=10),
        SkillNode(id="wiz_arcane_dmg_1", name="奥术掌控", description="增加奥术伤害",
                 node_type=NodeType.PASSIVE, position=(5, 2), max_points=5,
                 effects={"arcane_damage_percent": 5}, prerequisites=["wiz_spell_dmg_1"], required_level=25),
        SkillNode(id="wiz_crit_1", name="魔法暴击", description="法术暴击率",
                 node_type=NodeType.PASSIVE, position=(6, 1), max_points=5,
                 effects={"spell_crit_chance": 2}, prerequisites=["wiz_cast_speed_1"], required_level=30),
    ]


def create_demon_hunter_tree() -> List[SkillNode]:
    return [
        SkillNode(id="dh_dex_1", name="敏捷训练 I", description="增加敏捷",
                 node_type=NodeType.ATTRIBUTE, position=(0, 1), max_points=5,
                 effects={"dexterity": 3}, required_level=1),
        SkillNode(id="dh_dex_2", name="敏捷训练 II", description="大幅增加敏捷",
                 node_type=NodeType.ATTRIBUTE, position=(0, 2), max_points=5,
                 effects={"dexterity": 5}, prerequisites=["dh_dex_1"], required_level=10),
        SkillNode(id="dh_crit_1", name="精准瞄准", description="增加暴击率",
                 node_type=NodeType.PASSIVE, position=(1, 1), max_points=5,
                 effects={"crit_chance": 2}, required_level=1),
        SkillNode(id="dh_crit_dmg_1", name="致命射击", description="增加暴击伤害",
                 node_type=NodeType.PASSIVE, position=(1, 2), max_points=5,
                 effects={"crit_damage": 10}, prerequisites=["dh_crit_1"], required_level=15),
        SkillNode(id="dh_atk_speed_1", name="快速射击", description="增加攻击速度",
                 node_type=NodeType.PASSIVE, position=(2, 1), max_points=5,
                 effects={"attack_speed": 3}, required_level=5),
        SkillNode(id="dh_move_speed_1", name="灵活移动", description="增加移动速度",
                 node_type=NodeType.PASSIVE, position=(2, 2), max_points=5,
                 effects={"movement_speed": 2}, required_level=5),
        SkillNode(id="dh_dodge_1", name="闪避本能", description="增加闪避率",
                 node_type=NodeType.PASSIVE, position=(3, 1), max_points=5,
                 effects={"dodge_chance": 2}, prerequisites=["dh_move_speed_1"], required_level=10),
        SkillNode(id="dh_hated_1", name="仇恨积累", description="增加仇恨生成",
                 node_type=NodeType.PASSIVE, position=(4, 1), max_points=5,
                 effects={"hatred_generation": 10}, required_level=10),
        SkillNode(id="dh_disc_1", name="纪律训练", description="增加纪律上限",
                 node_type=NodeType.PASSIVE, position=(4, 2), max_points=5,
                 effects={"max_discipline": 5}, required_level=10),
        SkillNode(id="dh_dmg_1", name="猎魔之道", description="增加伤害",
                 node_type=NodeType.PASSIVE, position=(5, 1), max_points=5,
                 effects={"damage_percent": 3}, prerequisites=["dh_crit_dmg_1"], required_level=25),
        SkillNode(id="dh_life_steal_1", name="暗影汲取", description="攻击回复生命",
                 node_type=NodeType.PASSIVE, position=(5, 2), max_points=3,
                 effects={"life_steal": 1}, prerequisites=["dh_dmg_1"], required_level=30),
    ]


def create_monk_tree() -> List[SkillNode]:
    return [
        SkillNode(id="monk_dex_1", name="敏捷训练 I", description="增加敏捷",
                 node_type=NodeType.ATTRIBUTE, position=(0, 1), max_points=5,
                 effects={"dexterity": 3}, required_level=1),
        SkillNode(id="monk_dex_2", name="敏捷训练 II", description="大幅增加敏捷",
                 node_type=NodeType.ATTRIBUTE, position=(0, 2), max_points=5,
                 effects={"dexterity": 5}, prerequisites=["monk_dex_1"], required_level=10),
        SkillNode(id="monk_spirit_1", name="灵气汇聚", description="增加灵气回复",
                 node_type=NodeType.PASSIVE, position=(1, 1), max_points=5,
                 effects={"spirit_regen": 2}, required_level=1),
        SkillNode(id="monk_atk_speed_1", name="疾风连击", description="增加攻击速度",
                 node_type=NodeType.PASSIVE, position=(2, 1), max_points=5,
                 effects={"attack_speed": 3}, required_level=5),
        SkillNode(id="monk_dodge_1", name="流云步", description="增加闪避率",
                 node_type=NodeType.PASSIVE, position=(2, 2), max_points=5,
                 effects={"dodge_chance": 2}, required_level=5),
        SkillNode(id="monk_crit_1", name="会心一击", description="增加暴击率",
                 node_type=NodeType.PASSIVE, position=(3, 1), max_points=5,
                 effects={"crit_chance": 2}, prerequisites=["monk_atk_speed_1"], required_level=15),
        SkillNode(id="monk_holy_dmg_1", name="神圣之力", description="增加神圣伤害",
                 node_type=NodeType.PASSIVE, position=(3, 2), max_points=5,
                 effects={"holy_damage_percent": 5}, required_level=10),
        SkillNode(id="monk_resist_1", name="天人合一", description="增加所有抗性",
                 node_type=NodeType.PASSIVE, position=(4, 1), max_points=5,
                 effects={"all_resist": 5}, required_level=15),
        SkillNode(id="monk_life_on_hit_1", name="精气吸收", description="击中回复生命",
                 node_type=NodeType.PASSIVE, position=(4, 2), max_points=3,
                 effects={"life_on_hit": 50}, prerequisites=["monk_spirit_1"], required_level=20),
        SkillNode(id="monk_dmg_1", name="武道宗师", description="增加伤害",
                 node_type=NodeType.PASSIVE, position=(5, 1), max_points=5,
                 effects={"damage_percent": 3}, prerequisites=["monk_crit_1"], required_level=30),
    ]


def create_necromancer_tree() -> List[SkillNode]:
    return [
        SkillNode(id="necro_int_1", name="智力训练 I", description="增加智力",
                 node_type=NodeType.ATTRIBUTE, position=(0, 1), max_points=5,
                 effects={"intelligence": 3}, required_level=1),
        SkillNode(id="necro_int_2", name="智力训练 II", description="大幅增加智力",
                 node_type=NodeType.ATTRIBUTE, position=(0, 2), max_points=5,
                 effects={"intelligence": 5}, prerequisites=["necro_int_1"], required_level=10),
        SkillNode(id="necro_essence_1", name="精华汲取", description="增加精华回复",
                 node_type=NodeType.PASSIVE, position=(1, 1), max_points=5,
                 effects={"essence_regen": 2}, required_level=1),
        SkillNode(id="necro_minion_1", name="亡灵大军", description="增加召唤物伤害",
                 node_type=NodeType.PASSIVE, position=(2, 1), max_points=5,
                 effects={"minion_damage_percent": 5}, required_level=5),
        SkillNode(id="necro_minion_health_1", name="不死之身", description="增加召唤物生命",
                 node_type=NodeType.PASSIVE, position=(2, 2), max_points=5,
                 effects={"minion_health_percent": 10}, required_level=5),
        SkillNode(id="necro_bone_dmg_1", name="骨甲精通", description="增加骨系伤害",
                 node_type=NodeType.PASSIVE, position=(3, 1), max_points=5,
                 effects={"bone_damage_percent": 5}, prerequisites=["necro_int_1"], required_level=15),
        SkillNode(id="necro_poison_dmg_1", name="剧毒掌握", description="增加毒素伤害",
                 node_type=NodeType.PASSIVE, position=(3, 2), max_points=5,
                 effects={"poison_damage_percent": 5}, required_level=10),
        SkillNode(id="necro_life_steal_1", name="灵魂收割", description="攻击回复生命",
                 node_type=NodeType.PASSIVE, position=(4, 1), max_points=3,
                 effects={"life_steal": 1}, prerequisites=["necro_bone_dmg_1"], required_level=20),
        SkillNode(id="necro_crit_1", name="死亡之触", description="增加暴击率",
                 node_type=NodeType.PASSIVE, position=(4, 2), max_points=5,
                 effects={"crit_chance": 2}, required_level=15),
        SkillNode(id="necro_dmg_1", name="死亡领主", description="增加伤害",
                 node_type=NodeType.PASSIVE, position=(5, 1), max_points=5,
                 effects={"damage_percent": 3}, prerequisites=["necro_life_steal_1"], required_level=30),
    ]


def create_crusader_tree() -> List[SkillNode]:
    return [
        SkillNode(id="crus_str_1", name="力量训练 I", description="增加力量",
                 node_type=NodeType.ATTRIBUTE, position=(0, 1), max_points=5,
                 effects={"strength": 3}, required_level=1),
        SkillNode(id="crus_str_2", name="力量训练 II", description="大幅增加力量",
                 node_type=NodeType.ATTRIBUTE, position=(0, 2), max_points=5,
                 effects={"strength": 5}, prerequisites=["crus_str_1"], required_level=10),
        SkillNode(id="crus_armor_1", name="钢铁意志", description="增加护甲",
                 node_type=NodeType.PASSIVE, position=(1, 1), max_points=5,
                 effects={"armor": 15}, required_level=1),
        SkillNode(id="crus_block_1", name="盾牌精通", description="增加格挡率",
                 node_type=NodeType.PASSIVE, position=(2, 1), max_points=5,
                 effects={"block_chance": 3}, required_level=5),
        SkillNode(id="crus_thorns_1", name="荆棘之甲", description="增加反伤",
                 node_type=NodeType.PASSIVE, position=(2, 2), max_points=5,
                 effects={"thorns": 20}, required_level=5),
        SkillNode(id="crus_holy_dmg_1", name="神圣之力", description="增加神圣伤害",
                 node_type=NodeType.PASSIVE, position=(3, 1), max_points=5,
                 effects={"holy_damage_percent": 5}, prerequisites=["crus_str_1"], required_level=15),
        SkillNode(id="crus_wrath_1", name="神圣愤怒", description="增加愤怒生成",
                 node_type=NodeType.PASSIVE, position=(3, 2), max_points=5,
                 effects={"wrath_generation": 10}, required_level=10),
        SkillNode(id="crus_resist_1", name="圣光庇护", description="增加所有抗性",
                 node_type=NodeType.PASSIVE, position=(4, 1), max_points=5,
                 effects={"all_resist": 5}, prerequisites=["crus_armor_1"], required_level=20),
        SkillNode(id="crus_crit_1", name="审判之锤", description="增加暴击率",
                 node_type=NodeType.PASSIVE, position=(4, 2), max_points=5,
                 effects={"crit_chance": 2}, required_level=15),
        SkillNode(id="crus_dmg_1", name="十字军", description="增加伤害",
                 node_type=NodeType.PASSIVE, position=(5, 1), max_points=5,
                 effects={"damage_percent": 3}, prerequisites=["crus_holy_dmg_1"], required_level=30),
    ]


def create_druid_tree() -> List[SkillNode]:
    return [
        SkillNode(id="druid_str_1", name="力量训练 I", description="增加力量",
                 node_type=NodeType.ATTRIBUTE, position=(0, 1), max_points=5,
                 effects={"strength": 3}, required_level=1),
        SkillNode(id="druid_int_1", name="智力训练 I", description="增加智力",
                 node_type=NodeType.ATTRIBUTE, position=(1, 1), max_points=5,
                 effects={"intelligence": 3}, required_level=1),
        SkillNode(id="druid_nature_1", name="自然之力", description="增加自然伤害",
                 node_type=NodeType.PASSIVE, position=(2, 1), max_points=5,
                 effects={"nature_damage_percent": 5}, required_level=5),
        SkillNode(id="druid_shapeshift_1", name="变形大师", description="增加变形伤害",
                 node_type=NodeType.PASSIVE, position=(2, 2), max_points=5,
                 effects={"shapeshift_damage_percent": 5}, required_level=5),
        SkillNode(id="druid_summon_1", name="野性呼唤", description="增加召唤物伤害",
                 node_type=NodeType.PASSIVE, position=(3, 1), max_points=5,
                 effects={"summon_damage_percent": 5}, required_level=10),
        SkillNode(id="druid_fire_dmg_1", name="火焰掌控", description="增加火焰伤害",
                 node_type=NodeType.PASSIVE, position=(3, 2), max_points=5,
                 effects={"fire_damage_percent": 5}, required_level=10),
        SkillNode(id="druid_cold_dmg_1", name="风暴掌控", description="增加冰冷伤害",
                 node_type=NodeType.PASSIVE, position=(3, 3), max_points=5,
                 effects={"cold_damage_percent": 5}, required_level=10),
        SkillNode(id="druid_life_1", name="自然恢复", description="增加生命回复",
                 node_type=NodeType.PASSIVE, position=(4, 1), max_points=5,
                 effects={"health_regen": 10}, required_level=15),
        SkillNode(id="druid_crit_1", name="野性暴击", description="增加暴击率",
                 node_type=NodeType.PASSIVE, position=(4, 2), max_points=5,
                 effects={"crit_chance": 2}, required_level=15),
        SkillNode(id="druid_dmg_1", name="德鲁伊大师", description="增加伤害",
                 node_type=NodeType.PASSIVE, position=(5, 1), max_points=5,
                 effects={"damage_percent": 3}, prerequisites=["druid_nature_1"], required_level=30),
    ]


def create_assassin_tree() -> List[SkillNode]:
    return [
        SkillNode(id="asin_dex_1", name="敏捷训练 I", description="增加敏捷",
                 node_type=NodeType.ATTRIBUTE, position=(0, 1), max_points=5,
                 effects={"dexterity": 3}, required_level=1),
        SkillNode(id="asin_dex_2", name="敏捷训练 II", description="大幅增加敏捷",
                 node_type=NodeType.ATTRIBUTE, position=(0, 2), max_points=5,
                 effects={"dexterity": 5}, prerequisites=["asin_dex_1"], required_level=10),
        SkillNode(id="asin_crit_1", name="致命打击", description="增加暴击率",
                 node_type=NodeType.PASSIVE, position=(1, 1), max_points=5,
                 effects={"crit_chance": 2}, required_level=1),
        SkillNode(id="asin_crit_dmg_1", name="刺客之道", description="增加暴击伤害",
                 node_type=NodeType.PASSIVE, position=(1, 2), max_points=5,
                 effects={"crit_damage": 15}, prerequisites=["asin_crit_1"], required_level=15),
        SkillNode(id="asin_atk_speed_1", name="疾风连击", description="增加攻击速度",
                 node_type=NodeType.PASSIVE, position=(2, 1), max_points=5,
                 effects={"attack_speed": 3}, required_level=5),
        SkillNode(id="asin_dodge_1", name="影步", description="增加闪避率",
                 node_type=NodeType.PASSIVE, position=(2, 2), max_points=5,
                 effects={"dodge_chance": 2}, required_level=5),
        SkillNode(id="asin_shadow_dmg_1", name="暗影精通", description="增加暗影伤害",
                 node_type=NodeType.PASSIVE, position=(3, 1), max_points=5,
                 effects={"shadow_damage_percent": 5}, prerequisites=["asin_dex_1"], required_level=15),
        SkillNode(id="asin_trap_1", name="陷阱大师", description="增加陷阱伤害",
                 node_type=NodeType.PASSIVE, position=(3, 2), max_points=5,
                 effects={"trap_damage_percent": 5}, required_level=10),
        SkillNode(id="asin_move_speed_1", name="疾风步", description="增加移动速度",
                 node_type=NodeType.PASSIVE, position=(4, 1), max_points=5,
                 effects={"movement_speed": 3}, prerequisites=["asin_dodge_1"], required_level=20),
        SkillNode(id="asin_dmg_1", name="暗影宗师", description="增加伤害",
                 node_type=NodeType.PASSIVE, position=(5, 1), max_points=5,
                 effects={"damage_percent": 3}, prerequisites=["asin_shadow_dmg_1"], required_level=30),
    ]


def create_core_tree() -> List[SkillNode]:
    return [
        SkillNode(id="core_health_1", name="生命强化 I", description="增加生命值",
                 node_type=NodeType.ATTRIBUTE, position=(0, 0), max_points=5,
                 effects={"max_health": 10}, required_level=1),
        SkillNode(id="core_health_2", name="生命强化 II", description="大幅增加生命值",
                 node_type=NodeType.ATTRIBUTE, position=(0, 1), max_points=5,
                 effects={"max_health": 20}, prerequisites=["core_health_1"], required_level=10),
        SkillNode(id="core_mana_1", name="法力强化 I", description="增加法力值",
                 node_type=NodeType.ATTRIBUTE, position=(1, 0), max_points=5,
                 effects={"max_mana": 10}, required_level=1),
        SkillNode(id="core_mana_2", name="法力强化 II", description="大幅增加法力值",
                 node_type=NodeType.ATTRIBUTE, position=(1, 1), max_points=5,
                 effects={"max_mana": 20}, prerequisites=["core_mana_1"], required_level=10),
        SkillNode(id="core_damage_1", name="伤害强化 I", description="增加伤害",
                 node_type=NodeType.ATTRIBUTE, position=(2, 0), max_points=5,
                 effects={"damage_percent": 1}, required_level=1),
        SkillNode(id="core_damage_2", name="伤害强化 II", description="大幅增加伤害",
                 node_type=NodeType.ATTRIBUTE, position=(2, 1), max_points=5,
                 effects={"damage_percent": 2}, prerequisites=["core_damage_1"], required_level=15),
        SkillNode(id="core_armor_1", name="护甲强化 I", description="增加护甲",
                 node_type=NodeType.ATTRIBUTE, position=(3, 0), max_points=5,
                 effects={"armor": 5}, required_level=1),
        SkillNode(id="core_armor_2", name="护甲强化 II", description="大幅增加护甲",
                 node_type=NodeType.ATTRIBUTE, position=(3, 1), max_points=5,
                 effects={"armor": 10}, prerequisites=["core_armor_1"], required_level=15),
        SkillNode(id="core_resist_1", name="抗性强化", description="增加所有抗性",
                 node_type=NodeType.PASSIVE, position=(4, 0), max_points=5,
                 effects={"all_resist": 3}, required_level=10),
        SkillNode(id="core_regen_1", name="生命回复", description="增加生命回复",
                 node_type=NodeType.PASSIVE, position=(4, 1), max_points=5,
                 effects={"health_regen": 5}, required_level=10),
        SkillNode(id="core_crit_1", name="暴击精通", description="增加暴击率",
                 node_type=NodeType.PASSIVE, position=(5, 0), max_points=5,
                 effects={"crit_chance": 1}, required_level=20),
        SkillNode(id="core_crit_dmg_1", name="暴击伤害", description="增加暴击伤害",
                 node_type=NodeType.PASSIVE, position=(5, 1), max_points=5,
                 effects={"crit_damage": 5}, prerequisites=["core_crit_1"], required_level=25),
    ]


def register_all_skill_trees():
    all_nodes = (
        create_core_tree() +
        create_barbarian_tree() +
        create_wizard_tree() +
        create_demon_hunter_tree() +
        create_monk_tree() +
        create_necromancer_tree() +
        create_crusader_tree() +
        create_druid_tree() +
        create_assassin_tree()
    )
    return all_nodes
